language: node_js
cache: yarn
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - cd /app
  - yarn
script:
  - yarn test
